### ISSUE TITLE
dots in resource names warning

### ISSUE THREAD

**Issue by keen99** [dtan4/terraforming#123]
````
Warnings:

  * aws_iam_user.david.raistrick: david.raistrick: resource name can only contain letters, numbers, dashes, and underscores.
This will be an error in Terraform 0.4
````

iamu created:

````
resource "aws_iam_user" "david.raistrick" {
    name = "david.raistrick"
    path = "/"
}

"aws_iam_user.david.raistrick": {
     "type": "aws_iam_user",
          "primary": {
               "id": "david.raistrick",
               "attributes": {
....
````

The userid is allowed to have dots, but not the logical name - can we munge these when terraforming creates them in some fashion?

For someone else who runs into this - I just dropped the dot from the .tf and the .tfstate entries, and terraform is happy now.

**Comment by dtan4** [comment]
I fixed this issue by #129 not to include dots in module name, and released it as v0.3.0 :shipit: Please try this.

If you still have any problem, please reopen this issue.
