### ISSUE TITLE
empty option "iops" on root_block_device causes syntax error

### ISSUE THREAD

**Issue by colinmutter** [dtan4/terraforming#131]
On root_block_device, with type "standard", iops are not normally provided.  The generated output from terraforming however is an iops variable set to nothing, which causes syntax errors.

```
    root_block_device {
        volume_type           = "standard"
        volume_size           = 8
        iops                        =
        delete_on_termination = true
    }
```

Causes a syntax error when running terraform plan.  Removing the empty iops deifnition resolves it.

**Comment by dtan4** [comment]
@colinmutter Sorry for late response... I've fixed this bug at #132 and released as v0.3.2 :shipit: 
If you still have any problem, please reopen this issue.
