### ISSUE TITLE
Route table support is incomplete

### ISSUE THREAD

**Issue by kovyrin** [dtan4/terraforming#145]
Hey guys,

Since 0.5.0 terraforming seems to support route_table resources. But there is an issue with the level of support implemented. It only works correctly for route tables w/o any routes. The reason is that current implementation does not generate routes in tfstate, causing terraform to try to change the routes in AWS route tables while they are perfectly correct.

I believe this is an issue and terraforming should actually generate route blocks in tfstate.

**Comment by kovyrin** [comment]
I'm currently trying to implement the routes tfstate and will update the ticket on the progress.

**Comment by dtan4** [comment]
This issue is fixed at #146 and released as v0.6.2 :rocket: Thanks :exclamation:
