### ISSUE TITLE
Exporting route table associations could cause terraforming to crash

### ISSUE THREAD

**Issue by kovyrin** [dtan4/terraforming#147]
When there is an implicit route table association, AWS API returns an `Aws::EC2::Types::RouteTableAssociation` record, but it does not have a `subnet_id` value. ERB template for generating terraform files has logic to skip those records, but tfstate formatting code does not. This allows those records to get merged into the terraform state file and terraform starts to crash while processing those files.

**Comment by dtan4** [comment]
This issue is fixed at #148 and released as v0.6.2 :rocket: Thanks :exclamation:
