### ISSUE TITLE
Introduce Plugin-based architecture

### ISSUE THREAD

**Issue by dtan4** [dtan4/terraforming#152]
## WHY

Terraform itself supports [a lot of providers](https://www.terraform.io/docs/providers/), e.g. AWS, DigitalOcean, GCE, DNSimple ... Terraforming should also support them in the future.

I created [terraforming-dnsimple](https://github.com/dtan4/terraforming-dnsimple) to export DNSimple records & zones into tf & tfstate. This is a independent CLI tool, and maybe incompatible with (AWS-supported) Terraforming now. We want to use other provider with the same command `terraforming`, however, I don't want to include dependencies of other providers in this repository.
## WHAT

Implement plugin-loader in Terraform. Plugin-loader loads gems named `terraforming-{provider}` automatically.

This is a sample code to find  the _latest_ `terraforming-{provider}` gems from installed gems.

``` ruby
specs = Gem::Specification.find_all.select { |spec| spec.name =~ /\Aterraforming-.+\z/ }.group_by { |spec| spec.name }.values.map do |gems|
  gems.sort_by { |spec| spec.version }.last
end
```

And also, remove CLI from current terraforming-dnsimple. It will have only the library.
## REF
- [Plugin-based software design with Ruby and RubyGems](http://www.slideshare.net/frsyuki/pluginbased-software-design-with-ruby-and-rubygems)

**Comment by joshuajabbour** [comment]
Great idea; terraforming should be so much more than AWS. I've created a [CloudFlare DNS plugin](https://github.com/attn/terraforming-cloudflare) (which is just a fork of your DNSimple one). I will gladly convert this to a proper plugin when this support lands...

**Comment by dtan4** [comment]
This is very stale. I'll reopen this once I come up with the new idea.
