### ISSUE TITLE
Ox gem 2.2.2 fails

### ISSUE THREAD

**Issue by dsklopp** [dtan4/terraforming#153]
Using the ox gem 2.2.2 fails with a name error, but 2.2.1 and earlier works.  Steps to repeat:

: dklopp ; gem install ox -v 2.2.2
Fetching: ox-2.2.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ox-2.2.2
Parsing documentation for ox-2.2.2
Installing ri documentation for ox-2.2.2
Done installing documentation for ox after 0 seconds
1 gem installed
: dklopp ; terraforming 
/Users/dklopp/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant Ox::Raw (NameError)
	from /Users/dklopp/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/dklopp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/terraforming-0.6.2/lib/terraforming.rb:2:in `<top (required)>'
	from /Users/dklopp/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/dklopp/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/dklopp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/terraforming-0.6.2/bin/terraforming:3:in `<top (required)>'
	from /Users/dklopp/.rbenv/versions/2.2.2/bin/terraforming:23:in `load'
	from /Users/dklopp/.rbenv/versions/2.2.2/bin/terraforming:23:in `<main>'
: dklopp ; gem uninstall ox 

You have requested to uninstall the gem:
	ox-2.2.2

terraforming-0.6.2 depends on ox (>= 0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled ox-2.2.2
: dklopp ; gem install ox -v 2.2.1
Fetching: ox-2.2.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ox-2.2.1
Parsing documentation for ox-2.2.1
Installing ri documentation for ox-2.2.1
Done installing documentation for ox after 0 seconds
1 gem installed
: dklopp ; terraforming 
Commands:
  terraforming asg             # AutoScaling Group
  terraforming dbpg            # Database Parameter Group
  terraforming dbsg            # Database Security Group
  terraforming dbsn            # Database Subnet Group
  terraforming ec2             # EC2
  terraforming ecc             # ElastiCache Cluster
  terraforming ecsn            # ElastiCache Subnet Group
  terraforming eip             # EIP
  terraforming elb             # ELB
  terraforming help [COMMAND]  # Describe available commands or one specific command
  terraforming iamg            # IAM Group
  terraforming iamgm           # IAM Group Membership
  terraforming iamgp           # IAM Group Policy
  terraforming iamip           # IAM Instance Profile
  terraforming iamp            # IAM Policy
  terraforming iamr            # IAM Role
  terraforming iamrp           # IAM Role Policy
  terraforming iamu            # IAM User
  terraforming iamup           # IAM User Policy
  terraforming nacl            # Network ACL
  terraforming nif             # Network Interface
  terraforming r53r            # Route53 Record
  terraforming r53z            # Route53 Hosted Zone
  terraforming rds             # RDS
  terraforming rt              # Route Table
  terraforming rta             # Route Table Association
  terraforming s3              # S3
  terraforming sg              # Security Group
  terraforming sn              # Subnet
  terraforming vpc             # VPC

Options:
  [--merge=MERGE]                  # tfstate file to merge
  [--overwrite], [--no-overwrite]  # Overwrite existng tfstate
  [--tfstate], [--no-tfstate]      # Generate tfstate
  [--profile=PROFILE]              # AWS credentials profile

: dklopp ;

**Comment by dtan4** [comment]
I tested Ox 2.2.2 + Terraforming 0.6.2 on Ruby 2.2.2 / 2.2.3  on Mac OS X (maybe the same with your environment), and there was no error...

Let me investigate more details.

**Comment by dsklopp** [comment]
Here are my versions:

: dklopp @ Daniels-MBP ; ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
: dklopp @ Daniels-MBP ; 

Using Mac, version 10.11.1

**Comment by olly** [comment]
I just ran into the same issue:

```
$ terraforming r53z
/usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant Ox::Raw (NameError)
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/terraforming-0.6.2/lib/terraforming.rb:2:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/terraforming-0.6.2/bin/terraforming:3:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.0/bin/terraforming:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.0/bin/terraforming:23:in `<main>'
```

Installing v2.2.1, resolved the issue for me:

```
$ gem uninstall ox
$ gem install ox -v2.2.1
```

I was using Ruby 2.2.0, with RubyGems 2.4.5 on Mac OS X 10.11.2:
```
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

$ gem -v
2.4.5
```

**Comment by dcosson** [comment]
I got this error too fwiw - OSX El Capitan, Ruby 2.2.2. Installing Ox v2.2.1 also fixed it for me.

**Comment by dtan4** [comment]
I updated the least Ox version to v2.4.0, which is the latest version as of today, at #210.
Please check again with the current master branch.

**Comment by dtan4** [comment]
I've releaased Terraforming v0.8.0 which uses Ox v2.4.0. Please try this version.
If you still have the same problem, please reopen this issue.

**Comment by AndrewFarley** [comment]
Reopen please, just happened to me on...

terraforming-0.9.0 (latest as of today)
ox-2.4.1 (latest as of today)
OS-X 10.11.5 (latest as of today)
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14] (ruby that comes with this version of osx)

Modifying the gemspec file to point to ox 2.2.1, 2.2.2 and installing those versions of OX fixes the problem.  I tried 2.2.4 since it was the latest on the 2.2.x and 2.2.4 still has the Ox::Raw (NameError) bug.
