### ISSUE TITLE
Not all records returned for route53 (and possibly others)

### ISSUE THREAD

**Issue by seanodonnell** [dtan4/terraforming#159]
I realized while using terraforming that I was only getting results back for my first 100 records. I'm not a ruby dev, but after poking around the code, it looks like paging through records where there are more than 100 is not implemented.

Looking at http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/Route53/Client.html#list_resource_record_sets-instance_method

and 

http://docs.aws.amazon.com/Route53/latest/APIReference/API_ListResourceRecordSets.html

It would appear only the first 100 records are returned by default.  I'm not a Ruby developer, but I cant see any sign of looping to get the next batch of records in route53_record.rb

**Comment by seanodonnell** [comment]
This seems to be related

https://github.com/aws/aws-sdk-ruby/issues/620

**Comment by seanodonnell** [comment]
And here is a fix in puppet for what looks like the same problem

https://github.com/puppetlabs/puppetlabs-aws/pull/245/files

**Comment by seanodonnell** [comment]
Created a pull request with a fix https://github.com/dtan4/terraforming/pull/160

**Comment by dtan4** [comment]
This issue was fixed at #160 . Thank you @seanodonnell :exclamation:
