### ISSUE TITLE
is the docker container up-to-date?

### ISSUE THREAD

**Issue by jgangemi** [dtan4/terraforming#172]
i'm getting the following error trying to run the `igw` command via the docker container: `Could not find command "igw".`

is the container up-to-date w/ the latest version of `terraforming`?

thanks (and great tool!)

**Comment by dtan4** [comment]
I forgot the update of Docker image... I've just released new Docker image with the latest Terraforming (v0.7.0). :point_right: https://github.com/dtan4/dockerfile-terraforming/pull/20 Please check it.

Thank you for reporting :exclamation:
