### ISSUE TITLE
NameError when starting

### ISSUE THREAD

**Issue by Draftkings** [dtan4/terraforming#204]
Hello,

On windows, I get an error after typeing `terraforming` on the command line

Ruby: 2.2.4
Terraforming: 0.7.0

:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require': uninitialized constant Ox::Raw (NameError)
       from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
       from C:/Ruby22/lib/ruby/gems/2.2.0/gems/terraforming-0.7.0/lib/terraforming.rb:2:in `<top (required)>'
       from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
       from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
       from C:/Ruby22/lib/ruby/gems/2.2.0/gems/terraforming-0.7.0/bin/terraforming:3:in `<top (required)>'
       from C:/Ruby22/bin/terraforming:23:in `load'
       from C:/Ruby22/bin/terraforming:23:in `<main>'

**Comment by dtan4** [comment]
This issue is duplicated with #153 .
