### ISSUE TITLE
tfstate converts lists to #

### ISSUE THREAD

**Issue by kbroughton** [dtan4/terraforming#214]
terraforming version 0.7.1 running 
terraforming vpc --tfstate or any other command, terraforming displays lists as # .
I would expect to see all the tags, or the contents of whatever list.
```
{
  "version": 1,
  "serial": 1,
  "modules": [
    {
    ....
      "resources": {
        "aws_vpc.BaseStack": {
          "type": "aws_vpc",
          "primary": {
            "id": "vpc-fd****",
            "attributes": {
              "cidr_block": "10.201.0.0/21",
              ...
              "tags.#": "6"
            }
          }
        },

              "ebs_block_device.#": "4",
```

Some resources to manage lists correctly:
```
        "aws_route_table.Name-public": {
          "type": "aws_route_table",
          "primary": {
            "id": "rtb-3f****",
            "attributes": {
              "id": "rtb-3fa***",
              "vpc_id": "vpc-6b***",
              "tags.#": "6",
              "tags.cleardata:customer-id": "****",
              "tags.aws:cloudformation:stack-name": "****",
              "tags.aws:cloudformation:stack-id": "arn:aws:cloudformation:us-west-2:66xxx584:stack/
```

**Comment by dtan4** [comment]
It's okay. If there is the number of items in list `tags.#`, `terraform plan` complements other items.
Thanks to this behavior, we don't have to implement to include all list items in generated tfstate.

Actually `aws_route_table` doesn't have to include all tagged items. I missed this at code review 👀 

I'll write this behavior in v1.0.0 document. Thanks!

**Comment by kbroughton** [comment]
Actually, I think there is a good use case for having the expanded tags in the output.

soapy1 and I have been working on the filtering issue.
https://github.com/dtan4/terraforming/issues/79

The most common way to filter is on vpc-id or tag.  Without the expanded tags, there's no way to do that.

This is still quite a WIP, but it is working for my needs at the moment:

https://github.com/dtan4/terraforming/pull/215
