### ISSUE TITLE
Rate Limit Option for AWS Resources

### ISSUE THREAD

**Issue by liangyungong** [dtan4/terraforming#227]
Add an option for rate limit?
I got "exceed aws rate limit" error during execution.

**Comment by dtan4** [comment]
There is no way to configure maximum API rate limit.
If you got rate limit error, please wait for some time and retry.

## REF
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#api-request-rate

**Comment by tushar-dadlani** [comment]
@dtan4 Is there a way we can have retry logic inbuilt into the system? What if you have a lot of resources and the user reaches a rate limit since it's polling for a lot of information ?
