### ISSUE TITLE
eip.tf generated with non-existent key

### ISSUE THREAD

**Issue by Mikevin** [dtan4/terraforming#233]
Generating the eip.tf file results in an invalid file when there's an eip without attached instance.

Without an instance to specify, terraforming specifies the network interface ID.
It uses network_interface_id as the key for this value. This, however, is not a valid key in terraform.

According to the [documentation](https://www.terraform.io/docs/providers/aws/r/eip.html#network_interface) this key is supposed to be "network_interface", not "network_interface_id".

Seems like a small fix is required, it does load the correct value, just uses the wrong notation for the key itself. Sadly I'm not able to fix this myself as I have never worked with Ruby. I guess the problem is in [this ](https://github.com/dtan4/terraforming/blob/master/lib/terraforming/template/tf/eip.erb)file.

**Comment by dtan4** [comment]
Thank you for reporting ❗ and sorry for late response 🙇 

I reproduced this on my account and I found it's just a typo. I'll fix this soon.
