### ISSUE TITLE
Having an issue with NAT Gateway in 0.9.1

### ISSUE THREAD

**Issue by alexmurray100** [dtan4/terraforming#245]
Been using terraforming for a while and I am using 0.9.1, but NAT Gateway support is not available as a resource. Tried clean install with gem, same issue. 

*** LOCAL GEMS ***

aws-sdk (2.3.21, 2.3.19)
aws-sdk-core (2.3.21, 2.3.19)
aws-sdk-resources (2.3.21, 2.3.19)
terraforming (0.9.1)
.....

**Comment by dtan4** [comment]
I'm sorry I haven't released the version including NAT support yet.
If you'd like to use this feature now, please install from the source code.

```bash
$ git clone https://github.com/dtan4/terraforming.git
$ cd terraforming
$ rake install
```

I'll release the new version in a week.

**Comment by alexmurray100** [comment]
Thank you.

**Comment by dtan4** [comment]
@alexmurray100 Sorry for being late! Terraforming v0.10.0 w/ NAT Gateway support was released.
You can get the latest version by `gem install terraforming -v 0.10.0`.
