### ISSUE TITLE
aws_iam_user_policy resource name can only contain letters, numbers, dashes, and underscores.

### ISSUE THREAD

**Issue by kim-toms** [dtan4/terraforming#277]
I used terraforming to extract the configuration of my account in AWS (which had been built artisanally), and later **terraform plan** complained that one users policy which had his user name as "user.name" had the above listed problem.

Checking in the console indicated that the Policy Name actually had a period in it, so I'm not sure if the problem is in Terraform or Terraforming.

**Comment by dtan4** [comment]
Sorry for late reply. Could you paste your tf (mask if needed) and the output of `terraform plan` if exists?

**Comment by nabarunchatterjee** [comment]
Facing the same problem. Dug a bit deeper and saw  that while the resource names for some iam modules e.g. iam_user were being [normalized](https://github.com/dtan4/terraforming/blob/master/lib/terraforming/util.rb#L12) as can be seen [here](https://github.com/dtan4/terraforming/blob/master/lib/terraforming/resource/iam_user.rb#L32) and [here](https://github.com/dtan4/terraforming/blob/master/lib/terraforming/template/tf/iam_user.erb#L2) using the function [module_name_of](https://github.com/dtan4/terraforming/blob/master/lib/terraforming/resource/iam_user.rb#L50), other modules like instance_profile, user_policy etc were not getting normalized.

Here is a sample output of the command

> terraform plan

`Errors:

  * aws_iam_user_policy.XXX.YYY_policygen-XXX.YYY-ZZZZZZZ: XXX.YYY_policygen-XXX.YYY-ZZZZZZZ: resource name can only contain letters, numbers, dashes, and underscores.`

The same problem also occurs while importing state file.

Will send PR if I get some time.
