### ISSUE TITLE
CloudWatch alarm command not working

### ISSUE THREAD

**Issue by AnudeepReddyJ21** [dtan4/terraforming#284]
Hi,

When I run 'terraforming cwa' I get an error saying "Could not find command cwa". Let me know if I am doing something wrong here. All the other commands are working fine.

Thanks,

Anudeep

**Comment by dtan4** [comment]
I released Terraform v0.11.0 including CloudWatch alarm support. Please try the latest version :)

**Comment by AnudeepReddyJ21** [comment]
Thank you 👍
