### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by kenichi-shibata** [dtan4/terraforming#309]
Any chance we can get a walkthrough how to install terraforming manually?
My internet is firewalled and cannot connect to ruby gems so 
`gem install terraforming` fails for me

**Comment by dtan4** [comment]
You can install Terraforming directly from source code (this repository).

```bash
$ git clone https://github.com/dtan4/terraforming.git
$ cd terraforming
$ rake install
```

...However, it may fail because Terraforming dependes on some other RubyGems. `gem install othergem` will occur internally.

If you still fail to install, I cannot find other ways to install. Sorry... 😭
