### ISSUE TITLE
provide sample iam policy required to run terraforming

### ISSUE THREAD

**Issue by emalloy** [dtan4/terraforming#314]
I will provide this when I have time, but wanted to capture before escaped my memory.

In certain cases, one may need to run terraforming with AWS access keypair belonging to a user with a very narrow permission scope. A sandboxed user, if you will.

Feature request:

In the documentation provide the *minimum* iam policy required to successfully run terraforming.

**Comment by dtan4** [comment]
Thank you for your proposal.

The body of IAM policy depends on resources what user wants to generate.
In other words, _full-access_ or _write_ permission is not necessary to run Terraforming. _Read-only_ permission (e.g. `Describe*`, `List*`) is only required (I think).
