### ISSUE TITLE
TFState broken

### ISSUE THREAD

**Issue by igmar** [dtan4/terraforming#340]
$ terraforming vpc
<output>

$ terraforming --tfstate vpc
Could not find command "__tfstate".

Installation is done using gem install terraforming
This is a recent OSX machine.

**Comment by mhristof** [comment]
try `terraforming vpc --tfstate`

**Comment by igmar** [comment]
Hmm.. That indeed works. Why haven't I thought of that. It's however a bug if you ask me : The order shouldn't matter, and it's not clearly stated that this is a requirement.

It might just qualify as improvement, since it's not really a bug.

**Comment by mhristof** [comment]
i think this has to do with [the way that the cmd line args are generated](https://github.com/dtan4/terraforming/blob/master/lib/terraforming/cli.rb). So `--tfstate` is an argument to `vpc` instead of `terraforming`

**Comment by dtan4** [comment]
The behavior is by design of [Thor CLI library](https://github.com/erikhuda/thor) (see [Global flags? · Issue #219 · erikhuda/thor](https://github.com/erikhuda/thor/issues/219)).
I'm sorry but I have no way to handle this anymore...
