### ISSUE TITLE
When will the next release be made (looking to use SNS importing)?

### ISSUE THREAD

**Issue by ttacon** [dtan4/terraforming#352]
Hi there @dtan4! Thanks for the awesome tool! I was wondering if could shed some light on when you'll be cutting the next release? I'd love to be able to use the SNS import functionality that was merged in May, however it looks like the last version (0.13.2) was cut just before it was merged.

Thanks again!

**Comment by coingraham** [comment]
@ttacon If you clone this repo and build the gem you can install it using the local copy from source.

`sudo gem uninstall terraforming
git clone https://github.com/dtan4/terraforming.git
cd terraforming
vi lib/template/version.rb (here I edited the version so I knew I was installing the local copy)
gem build terraforming.gemspec
sudo gem install terraforming-0.13.3.gem
terraforming help`

You'll see the new sns options available and be able to use them.  Once the actual gem is updated, you can uninstall and reinstall.

**Comment by ttacon** [comment]
Awesome, thanks for the instructions (although I found the version file under `lib/terraforming/version.rb`). This is more than helpful enough for me for now, ty again! Closing this ticket.

**Comment by dtan4** [comment]
@ttacon Sorry for late! I just released v0.14.0. Please try this 🙏

**Comment by coingraham** [comment]
@dtan4 No problem at all.  Love the tool and the work you're doing!
