### ISSUE TITLE
terraforming kmsk throws an exception

### ISSUE THREAD

**Issue by johnrizzo1** [dtan4/terraforming#361]
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.40/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': arn:aws:kms:us-east-1:925458006158:key/0132c156-85d0-4c60-b7a8-afd73a6f6c8b origin is EXTERNAL which is not valid for this operation. (Aws::KMS::Errors::UnsupportedOperationException)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.40/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.40/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.40/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.40/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.40/lib/seahorse/client/request.rb:70:in `send_request'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.40/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/terraforming-0.14.0/lib/terraforming/resource/kms_key.rb:68:in `key_rotation_status_of'
        from (erb):6:in `block in apply_template'
        from (erb):1:in `each'
        from (erb):1:in `apply_template'
        from C:/Ruby23-x64/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from C:/Ruby23-x64/lib/ruby/2.3.0/erb.rb:864:in `result'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/terraforming-0.14.0/lib/terraforming/util.rb:4:in `apply_template'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/terraforming-0.14.0/lib/terraforming/resource/kms_key.rb:19:in `tf'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/terraforming-0.14.0/lib/terraforming/resource/kms_key.rb:7:in `tf'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/terraforming-0.14.0/lib/terraforming/cli.rb:250:in `tf'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/terraforming-0.14.0/lib/terraforming/cli.rb:237:in `execute'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/terraforming-0.14.0/lib/terraforming/cli.rb:129:in `kmsk'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/terraforming-0.14.0/bin/terraforming:5:in `<top (required)>'
        from C:/Ruby23-x64/bin/terraforming:22:in `load'
        from C:/Ruby23-x64/bin/terraforming:22:in `<main>'

**Comment by dtan4** [comment]
Currently KMS external key is not supported by Terraform (terraform-provider-aws). There is [a patch to add `aws_kms_external_key` resource](https://github.com/terraform-providers/terraform-provider-aws/pull/1127), but it haven't been merged yet.

According to this, KMS external key should be ignored by `kmsk` command. I'll make a patch.
Thanks!
