### ISSUE TITLE
Terraforming multiple AWS regions

### ISSUE THREAD

**Issue by waghanza** [dtan4/terraforming#369]
Hello,

I work on several `AWS` regions. 

When I want to *terraform* actual stacks with a non-default account, terraforming fails.

It seem to be since region is taken from `default ` account.

Regards,

**Comment by dtan4** [comment]
I tried with multiple IAM users and multiple regions, it worked fine.
Terraforming v0.15.0

```
[default]
aws_access_key_id = ...
aws_secret_access_key = ...

[dtan4]
aws_access_key_id = ...
aws_secret_access_key = ...
```

```bash
# with default user
terraforming kmsa --region us-west-1
terraforming kmsa --region ap-northeast-1

# with non-default user
terraforming kmsa --profile dtan4 --region us-west-1
terraforming kmsa --profile dtan4 --region ap-northeast-1
```

It seems that we have nothing to do about this now.
Could you show me the error message?
