### ISSUE TITLE
aws_kms_key: "key_usage" must be ENCRYPT_DECRYPT or not specified

### ISSUE THREAD

**Issue by koooge** [dtan4/terraforming#373]
Hello. :)
`terraforming kmsk` generated below setting.
But `terraform plan` with the .tf file shows `aws_kms_key: "key_usage" must be ENCRYPT_DECRYPT or not specified` error.
Is this intended?

```
resource "aws_kms_key" "<id>" {
    description             = ""
    key_usage               = "ENCRYPT/DECRYPT"
    is_enabled              = true
    enable_key_rotation     = false

    policy = <<POLICY
...
```

**Comment by dtan4** [comment]
This is a bug appearently, thanks! I'll fix.

**Comment by dtan4** [comment]
Fixed at https://github.com/dtan4/terraforming/pull/380 .

**Comment by dtan4** [comment]
I send a document patch to terraform-provider-aws, related to this.
https://github.com/terraform-providers/terraform-provider-aws/pull/2006
