### ISSUE TITLE
terraform plan recreates resources

### ISSUE THREAD

**Issue by rauizab** [dtan4/terraforming#375]
Hi
I have followed the instructions to export some resources, but if I do terraform plan it shows that he will try to create all resources again.

```
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_s3_bucket.*******
      id:                  <computed>
      acceleration_status: <computed>
      acl:                 "private"
      arn:                 <computed>
      bucket:              "bosh-backups"
      bucket_domain_name:  <computed>
      force_destroy:       "false"
      hosted_zone_id:      <computed>
      region:              <computed>
      request_payer:       <computed>
      versioning.#:        <computed>
      website_domain:      <computed>
      website_endpoint:    <computed>
....
```

**Comment by brunopadz** [comment]
Have you created tf files for S3? It also happened to me when I didn't have the resources in a .tf file.

**Comment by susannamartinelli** [comment]
@rauizab @brunopadz I have the same problem.
I ran  a _total_ export from my AWS infrastructure https://github.com/dtan4/terraforming#example-export-all and it created all `*.tf` files.
Then I ran the `.tfstate` export for each resource Eg:
  - the first one `terraforming <res> --profile default --tfstate > terraform.tfstate`
  - the others: `terraforming <res> --profile default --tfstate --merge terraform.tfstate --overwrite`

However when I run `terraform plan` it tries to destroy and recreate all resources, It seems to me that when it tries to recreate the `.tfstate` file from scratch from AWS existing resource it cannot replicate exactly these resources so the `terraform plan` see as modifications the '*.tf' files

**Comment by brunopadz** [comment]
Yeah, as I've said, I've ran into the same issue, but it did work when I created the tf files for that specific resource. Have you tried to use terraforming for only one resource?

**Comment by susannamartinelli** [comment]
@brunopadz Thanks 
I guess my problem is that I was trying to wrap all my legacy infrastructure as an unique module. 
Now seems to work fine.
However `terraform plan` replies with a number of resources that cannot be modified but only destroyed/recreated such as *launch.configurations* or *ec2.instance* but I think this depends from the fact that this kind of resources in AWS cannot be modified on the fly.
