### ISSUE TITLE
Apply in an already implemented environment

### ISSUE THREAD

**Issue by hutger** [dtan4/terraforming#393]
Hi, I've just tested Terraforming in my implemented environment and ran flawlessly. 

It can be a silly question but...  I was just wondering... what would happen if I forward the output to a .tf file and apply it in my environment, it will keep all the already existent objects (EC2 instances, VPCs, EBSs, and so on) or will try to replace it?

I mean... if I run "terraforming ec2", save the output to a .tf file (ec2.tf) and later run "terraform apply"?

**Comment by AnthonyWC** [comment]
If you run terraform plan and it will show you the difference between the terraform tf
configuration file to what's stored in your tfstate file (which should be sync to what's in your infrastructure).  So if you run terraform apply it will execute whatever is the difference in that plan, assuming that the tf plan is valid w/o error.

**Comment by hutger** [comment]
Hi @AnthonyWC, thanks for you reply. Now I get it.

**Comment by dtan4** [comment]
Terraform doesn't see and modify existing resource *ouf of* tfstate. Basically there is no problem for existing resources.

Thanks @AnthonyWC for your comment!
