### ISSUE TITLE
Any plans to support other providers?

### ISSUE THREAD

**Issue by robinbowes** [dtan4/terraforming#397]
Do you have any plans to support anything other than AWS?

The particular itch I need to scratch right now is `datadog_monitor` resources. I'm writing something myself, but would be good to support something other than AWS resources in terraforming.

I guess that would require a degree of restructuring, etc?

**Comment by meyerbro** [comment]
It would be great if you guys start supporting other providers... I would love to use it with github provider...

**Comment by romaric1** [comment]
I am making a project to generate terraform code from gcp ressources you can look it at  https://github.com/romaric1/gcp2Terraform   
please be free to make any feedback and contibuting to this project

**Comment by dtan4** [comment]
I wrote some Terraforming for other providers as independent tools:

- Datadog: https://github.com/dtan4/terraforming-datadog
- Google Kubernetes Engine (GKE): https://github.com/dtan4/terraforming-gke

I don't have any roadmap to support other providers for now. If you want Terraforming for other providers, please write it by yourself 🙇 
Thanks!
