### ISSUE TITLE
rt command

### ISSUE THREAD

**Issue by denzalman** [dtan4/terraforming#435]
if inside Route Table there is nat gateway - we can't see it in response info. only igw

**Comment by awin-automation-owner** [comment]
This is the resulting tf setting:
`    route {
        cidr_block = "0.0.0.0/0"
    }`

Instead it should be:
`    route {
        cidr_block = "0.0.0.0/0"
        nat_gateway_id = "nat-xxxxxxxxxx"
    }`

**Comment by ynuyasha** [comment]
i found the same issue
