### ISSUE TITLE
Running Terraform Plan and it says +24, 0 to delete, 0 to Chage.. does this mean it will recreate the resources which I already have 

### ISSUE THREAD

**Issue by netsticker** [dtan4/terraforming#441]
Hello Dan,

While running Terraform Plan. I am receiving result as:

Plan: 24 to add, 0 to change, 0 to destroy.

Does this mean it will recreate the resources.. I only have 24 resources so far, This is EC2.

I wanna add more but don't wanna do anything with my existing resources as some production apps are running.

Please advice.

Regards

**Comment by dtan4** [comment]
Terraform needs state file (tfstate) in addition to tf configurations. Terraform calculates the diff between this state file and tf configurations.

[State - Terraform by HashiCorp](https://www.terraform.io/docs/state/)

> Terraform must store state about your managed infrastructure and configuration. This state is used by Terraform to map real world resources to your configuration, keep track of metadata, and to improve performance for large infrastructures.

Therefore, you have to generate tfsate by Terraforming or [`terraform import` command](https://www.terraform.io/docs/commands/import.html).
