### ISSUE TITLE
Command terraforming dbpg generates invalid configuration

### ISSUE THREAD

**Issue by memberbetty** [dtan4/terraforming#448]
`terraforming dbpg`  generates values 

with an empty string instead of a valid value. 

Example of invalid Terraform code being generated:

```
    parameter {
        name         = "geqo_pool_size"
        value        = ""
        apply_method = "pending-reboot"
    }
```

**Comment by dtan4** [comment]
It works well in my environment. If the parameter has a value, it will be injected correctly.

![image](https://user-images.githubusercontent.com/680124/56472283-6ba00800-6497-11e9-9d60-d31d21cd70a1.png)

```sh-session
$ bundle exec bin/terraforming dbpg | grep -A 3 -B 1 basedir
    parameter {
        name         = "basedir"
        value        = "/rdsdbbin/oscar"
        apply_method = "pending-reboot"
    }
```

Additionally, it's usual that parameter doesn't have any value.

![image](https://user-images.githubusercontent.com/680124/56472330-08fb3c00-6498-11e9-9815-36c2343afd6e.png)

If this is not a correct answer to your question, please reopen this issue. Thanks!
