### ISSUE TITLE
Terraforming --version

### ISSUE THREAD

**Issue by abacao** [dtan4/terraforming#470]
Please allow a way to check the current version of terraforming.

**Comment by RanjitRajput** [comment]
You can use the below command to find out the terraforming version.
$ gem list | grep terraforming
terraforming (0.18.0)

**Comment by abacao** [comment]
That only works if you install the gem.
There is no way (that I could find) to check the version of the binary.

**Comment by BrianSidebotham** [comment]
+1 this would be really handy.
