### ISSUE TITLE
Tags incorrectly formatted when exporting EC2. 

### ISSUE THREAD

**Issue by ARSport** [dtan4/terraforming#487]
When doing the export to ec2 `terraforming ec2` the tags appear in the following format:
```
    tags {
        "Team" = "teamx"
        "Name" = "super-instance-new"
        "Purpose" = "production"
```
When trying to plan that, terraform (latest) complain about the format and have to manually correct to

```
    tags = {
        Team = "teamx"
        Name = "super-instance-new"
        Purpose = "production"
```

**Comment by negrusti** [comment]
this applies to tags everywhere, not just EC2

**Comment by ARSport** [comment]
I am closing this one in favor of #484 which haves a fix too.
