### ISSUE TITLE
When generating tfstate, modules should contain a list of hashes, not a hash

### ISSUE THREAD

**Issue by endemics** [dtan4/terraforming#55]
While trying to do a `terraform plan` on a generated tfstate for security groups, terraform exited with:
```
Error reading local state: Decoding state file failed: json: cannot unmarshal object into Go value of type []*terraform.ModuleState
```
(terraform 0.5.2)

In terraform/state.go:42, we have indeed:
```go
    Modules []*ModuleState `json:"modules"`
```

So `generate_tfstate` should have `"modules" => [ ... ]` instead of `"modules" => { ... }`

**Comment by dtan4** [comment]
@endemics Thank you for reporting this issue :exclamation: 
Despite this is a very basic bug, I've never noticed this...

(In fact I haven't use the entire generated tfstate with my usual work...)
