### ISSUE TITLE
name clash for 'default' security groups when combining classic + vpc, or several vpcs

### ISSUE THREAD

**Issue by endemics** [dtan4/terraforming#57]
When using `terraforming sg` in a context where you have either classic + vpc or several VPCs, terraforming creates resources with the name "default" (i-e lines of `resource "aws_security_group" "default"`).

In my opinion there is several ways to solve this (it can be combined):
- provide an option to ignore default groups in the resource generation + state generation
- automatically ignore default groups if they have not been modified
- use the 'vpc_id'  as a prefix for VPC default groups

**Comment by endemics** [comment]
Actually I believe this was fixed in e418582a056fe28c8a260f3cdb223bedaa38095a GMTA :)

**Comment by dtan4** [comment]
@endemics Thank you for reporting issue :exclamation: 

At #53 (yesterday!) I found that SecurityGroup names are sometimes duplicated, so I decided to add unique prefix `group_id` to resource name.

> provide an option to ignore default groups in the resource generation + state generation
> automatically ignore default groups if they have not been modified

These are good suggestions :+1: 
Default security groups are modifiable, but not deletable.
I think that these immutable(?) resources are not suitable to be managed under Terraform :sparkler: 

## REF

- [Security Groups for Your VPC - Amazon Virtual Private Cloud](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_SecurityGroups.html)

**Comment by endemics** [comment]
> I think that these immutable(?) resources are not suitable to be managed under Terraform :sparkler:

Yeah they are very problematic resources indeed.

I agree they shouldn't be managed by Terraform, especially when you're building your infra from scratch, and I assume most people won't try to manage them this way.

However, it's not that easy in the case of terraforming as people might want to use it to manage what they already have and they might have used default and tweaked them.

So I guess your tool will have to take a stance/be opiniated about this issue and document how it addresses it?

**Comment by dtan4** [comment]
Sorry for late response...

My opinion is that all resources, including default resources, should be exported by default. It has compatibility with all people using Terraforming.
However, in the near future, I might provide a option to omit default resources.

> So I guess your tool will have to take a stance/be opiniated about this issue and document how it addresses it?

Yes, I'll write about how to treat default resource.

Thank you for giving me the chance to think about this problem :smile:

**Comment by endemics** [comment]
No worries, thanks for looking into it :)
