### ISSUE TITLE
Support IAM Server Certificate

### ISSUE THREAD

**Issue by dtan4** [dtan4/terraforming#64]
## WHY
We need to handle existing server certificates by Terraform.

## WHAT
Add support for IAM Server Certificate.

## REF
- [AWS: aws_iam_server_certificate - Terraform by HashiCorp](https://www.terraform.io/docs/providers/aws/r/iam_server_certificate.html)

**Comment by BenElgar** [comment]
To confirm, was this done? Or was this deemed unnecessary?
