### ISSUE TITLE
Support AutoScaling

### ISSUE THREAD

**Issue by cristim** [dtan4/terraforming#83]
It would be nice to have a way to dump an entire AutoScaling group and its attached configuration (LaunchConfiguration, ELB, etc).

**Comment by dtan4** [comment]
Yeah it would be nice if this resource exists. Pull requests :octocat: are welcome :smile:

**Comment by johnwards** [comment]
@dtan4 Just wondering if LaunchConfiguration export is on the roadmap? (Sadly I don't think my ruby is up to a pull request :(

**Comment by dtan4** [comment]
Yes, I'd like to add more supports for other AutoScaling resources, incl. [LaunchConfiguration](https://www.terraform.io/docs/providers/aws/r/launch_configuration.html). However, it seems that LaunchConfiguration is complicated (like [EC2 instance](https://www.terraform.io/docs/providers/aws/r/instance.html)), so I couldn't have much time to implement this...

I recognize there is strong demand for AutoScaling support, so I'll try to have time and implement this as soon as possible :bow:

**Comment by johnwards** [comment]
@dtan4 great to hear. Thanks for the reply, really appreciated. 

Such a great tool you've built, really helped today :)

**Comment by dtan4** [comment]
Now AutoScaling Group and LaunchConfiguration are supported :shipit: Please try the latest version.
