### ISSUE TITLE
Support multi region

### ISSUE THREAD

**Issue by spesnova** [dtan4/terraforming#88]
I have AWS resources across 2 region.
However Currently terraforming outputs resources for only single region.
So please support multiple region

**Comment by dtan4** [comment]
Thank you for reporting issue :exclamation: 

In fact, it may be difficult to generate resources across multi-region at _the same time_ .

Terraforming loads `AWS_REGION` environment variable, so you can generate resources in _another_ region by switching AWS_REGION :earth_asia: 

To generate SecurityGroups in ap-northeast-1 (Tokyo) and ap-southeast-1 (Singapore):

```bash
# export AWS_REGION=ap-northeast-1
$ terraforming sg # SecurityGroup in ap-northeast-1
$ AWS_REGION=ap-southeast-1 terraforming sg # SecurityGroup in ap-southeast-1
```

**Comment by spesnova** [comment]
OK, It makes sense.
