### ISSUE TITLE
Ec2 updates error

### ISSUE THREAD

**Issue by monicagangwar** [dtan4/terraforming#93]
i'm retrieving the tf and tfstate files for ec2 using terraforming only but when i execute terraform plan it shows me various updates instead of no changes

**Comment by dtan4** [comment]
@monicagangwar Could you show me your tf, tfstate and the result of `terraform plan` ?
I'd like to confirm the detail of your issue...

**Comment by monicagangwar** [comment]
i cant exactly show you those files but the reason why terraform is forcing a new ec2 resource is because when i retrieve tfstate for ec2 its unable to fetch the security groups for the instances.

**Comment by dtan4** [comment]
OK, I'll investigate this.

**Comment by dtan4** [comment]
@monicagangwar Just released v0.1.2 including these fix :shipit: please try it.
If you have any problems at this version, please reopen this issue.
