### ISSUE TITLE
ec2 command imports root block device as ebs_block_device, forcing a new resource

### ISSUE THREAD

**Issue by zdexter** [dtan4/terraforming#95]
`terraforming ec2` imports what should be a `root_block_device` as an `ebs_block_device`, which causes terraform plans to force new ec2 resources.

Steps to reproduce:

1. Create an EBS-optimized EC2 instance with a root device type of `ebs` and some size, say 5 gB
2. Run `terraforming ec2`  
3. Observe the following incorrect output inside the `aws_instance` configuration block:

```
ebs_block_device {
    device_name = "/dev/sda1"
}
```

tfstate is also incorrect:

```
    ebs_block_device.#:                                "0" => "1"
    ebs_block_device.[removed].device_name:           "" => "/dev/sda1" (forces new resource)
    ebs_block_device.[removed].volume_size:           "" => "<computed>" (forces new resource)
    ebs_block_device.[removed].volume_type:           "" => "<computed>" (forces new resource)
    [ various other settings that force a new resource]
```

The output should be:

```
root_block_device {
    volume_size = 5
}
```

tfstate output from `terraform plan` is now correct:

```
    root_block_device.#:                       "1" => "1"
    [ various other settings that do not force a new resource ] 
```

`terraform` version: 0.6.0

`terraforming` version: 0.1.0

**Comment by dtan4** [comment]
@zdexter Just released v0.1.2 including this fix :shipit: please try it.
If you have any problems at this version, please reopen this issue.
