### ISSUE TITLE
ec2 command imports non-default-VPC security groups using the wrong directive, forcing a new resource

### ISSUE THREAD

**Issue by zdexter** [dtan4/terraforming#96]
Per the [Terraform instance documentation](https://www.terraform.io/docs/providers/aws/r/instance.html):

> security_groups - (Optional) A list of security group names to associate with. If you are within a non-default VPC, you'll need to use vpc_security_group_ids instead.

`terraforming ec2` will import EC2 instances created in a non-default VPC and put their security groups in a `security_groups` directive. However, as explained above, these security groups should be in a `vpc_security_group_ids` directive. Switching to the correct directive prevents `terraform` from forcing a new ec2 resource.

terraform version: 0.6.0

terraforming version: 0.1.0

**Comment by dtan4** [comment]
This should be fixed at #94 .
Thank you for reporting issue :octocat:

**Comment by dtan4** [comment]
@zdexter Just released v0.1.2 including this fix :shipit: please try it.
If you have any problems at this version, please reopen this issue.
